namespace SectigoCertificateManager;

/// <summary>
/// Enumerates known error codes returned by the API.
/// </summary>
public enum ApiErrorCode {
    UnknownError = -1,// Unknown error.
    InternalErrorPleaseContactSupportForDetails = -2,// Internal error. Please contact Support for details.
    YouAreNotAuthorizedToPerform0 = -3,// You are not authorized to perform {0}.
    CodeNeg7 = -7,// {0} is required but missing.
    UnknownNotificationType0 = -9,// Unknown notification type: {0}
    TheCsrIsNotValidBase64Data = -9,// The CSR is not valid Base-64 data!
    ErrorWhileDecodingCsr = -10,// Error while decoding CSR.
    TheCsrUsesAnUnsupportedAlgorithm = -11,// The CSR uses an unsupported algorithm!
    TheCsrUsesAnUnsupportedKeySize = -13,// The CSR uses an unsupported key size!
    UnknownErrorNeg14 = -14,// Unknown error.
    UnknownUser = -16,// Unknown user.
    YouAreNotAuthorizedToExecute0 = -25,// You are not authorized to execute {0}
    TheServerTypeIsInvalid = -35,// The Server type is invalid!
    TheValidityPeriodTermIsInvalidForThisCertificateProfile = -36,// The validity period (term) is invalid for this certificate profile.
    AccessDenied = -37,// Access denied.
    CodeNeg39 = -39,// {0}
    TheCertificateProfileIdIsInvalid = -39,// The certificate profile id is invalid!
    InternalErrorWhileDecrypting = -43,// Internal error while decrypting.
    ErrorWhileGeneratingKeyPairWithOpenSsl = -44,// Error while generating key pair with open SSL
    MissingMandatoryCustomField = -62,// Missing mandatory custom field!
    InvalidIpAddress0 = -62,// Invalid IP address {0}
    OptionalFieldNameIsInvalid = -64,// Optional field 'name' is invalid!
    InternalError0PleaseContactSupportForDetails = -65,// Internal error {0}. Please contact Support for details.
    KuekuTemplateIsNotAllowedForCustomer = -76,// KU/EKU template is not allowed for customer.
    ThePublicKeyIsInvalidOrNotSupported = -78,// The public key is invalid or not supported.
    OnlyIssuedCertificatesCouldBeRevoked = -102,// Only issued certificates could be revoked.
    CertificateHasNotBeenCollectedYet = -103,// Certificate has not been collected yet.
    PersonNotFound = -105,// Person not found.
    ErrorWasOccurredWhileRenewingCertStatus0 = -105,// Error was occurred while renewing cert. Status = {0}
    DomainControlValidationIsEitherIncompleteOrExpiredFor0PleaseCompleteItBeforeRequestingACertificate = -107,// Domain Control Validation is either incomplete or expired for {0}. Please complete it before requesting a certificate.
    CertificateIsNotAvailableNowPleaseTryAgainLater = -109,// Certificate is not available now, please try again later.
    CertificateHasBeenRevokedAndCannotBeDownloaded = -110,// Certificate has been revoked and cannot be downloaded.
    NoCertificateProfileFoundById0 = -111,// No certificate profile found by id {0}
    SslCertificateToRenewIsInvalidNull = -123,// SSL Certificate to renew is invalid (null)
    WrongSslCertificateId0 = -124,// Wrong SSL certificate id {0}.
    UnknownSslCertificateFileFormatRequested0 = -126,// Unknown SSL certificate file format requested: {0}
    ConnectionErrorWhileApplyingCertificate = -129,// Connection error while applying certificate.
    SslStateIsNotIssued0 = -130,// SSL state is not ''ISSUED'': {0}
    CustomFieldsLimitExceededForCustomer = -131,// Custom fields limit exceeded for customer.
    CustomFieldHasToHaveUniqueName = -134,// Custom field has to have unique name.
    CustomFieldCannotBeFound = -135,// Custom field cannot be found.
    InvalidCsr = -138,// Invalid CSR.
    CsrDecodingTemporarilyUnavailablePleaseTryAgainLater = -140,// CSR decoding temporarily unavailable. Please try again later.
    ThePublicKeySizeInTheCsrShouldBe0BitsMinimum = -141,// The public key size in the CSR should be {0} bits minimum.
    YourCertificateAlreadyRevoked = -159,// Your certificate already revoked
    CustomFieldsLimitHasBeenExceededForThisCustomerOnly0CustomFieldsOrFewerAreAllowed = -159,// Custom fields limit has been exceeded for this customer. Only {0} custom fields or fewer are allowed.
    YouCantCreateFieldsWithTheSameName0 = -160,// You can''t create fields with the same name - {0}!
    CertificateCannotBeEnrolledForALocalDomainAndorPrivateIpForAValidityPeriodExceeding0 = -164,// Certificate cannot be enrolled for a Local Domain and/or Private IP for a validity period exceeding {0}.
    EnteredDataDoesntMatchTheCertificateOrNoValidCertificateFound = -166,// Entered data doesn''t match the certificate or no valid certificate found
    CertificateIsNotAvailablePleaseContactAdministrator = -169,// Certificate is not available, please contact administrator.
    BasedOnTheCustomerConfigurationEccCsrsAreNotAllowed = -170,// Based on the customer configuration, ECC CSRs are not allowed.
    TheClientCertificateProfileIsInvalid = -172,// The Client Certificate Profile is invalid!
    UpdatingIsNotPossibleListOfYourClientCertificateProfileWasChangedBySuperAdmin = -176,// Updating is not possible. List of your Client Certificate Profile was changed by super admin.
    ThisSslCertificateProfileDoesntAllowRenew = -180,// This SSL Certificate Profile doesn''t allow renew
    AnchorCertificateDetailsDoNotMatchToYourRequest = -181,// Anchor Certificate details do not match to your request.
    CertificateIsNotCollectable = -183,// Certificate is not collectable.
    ObjectHasNoAvailableCustomizedClientCertificateProfile = -184,// Object has no available customized Client Certificate Profile.
    CustomizedClientCertificateProfile0HasNoAvailableTerms = -185,// Customized Client Certificate Profile: {0} has no available terms.
    ThisUserHaveAlreadyReachedTheMaximumAllowedNumberOfValidCertificates0 = -188,// This user have already reached the maximum allowed number of valid certificates: {0}
    TheCsrUsesAnUnsupportedKeySizeNeg194 = -194,// The CSR uses an unsupported key size.
    CaIsNotAvailableNowPleaseTryAgainLater = -195,// CA is not available now. Please try again later.
    ConnectionErrorWhileRetrievingDcvEmailList = -196,// Connection error while retrieving DCV email list.
    OldPasswordIsIncorrect = -213,// Old password is incorrect
    CannotChangeTheRoleOfTheOnly0User = -219,// Cannot change the role of the only {0} user.
    PasswordCantBeTheSame = -220,// Password can''t be the same.
    PleaseSelectAtLeastOneOrganizationdepartmentForEachSelectedRole = -221,// Please select at least one Organization/Department for each selected role
    PleaseSelectRolesForTheSameLevel = -222,// Please select roles for the same level
    PleaseSelectOnlyOneOrganizationdepartmentForEachSelectedRole = -223,// Please select only one Organization/Department for each selected role
    ThisAdminAccountDoesNotHavePrivilegesRequiredToManage0Org = -226,// This Admin account does not have privileges required to manage ''{0}'' &lt;org&gt;.
    YouHaveNoPrivilegeToCreateThisAdminUser = -233,// You have no privilege to create this admin user.
    YouHaveNoPrivilegeToModifyThePrivilegesOfThisAdmin = -234,// You have no privilege to modify the privileges of this admin.
    ClientAdminsEmailIsInvalid = -237,// Client Admin''s Email is invalid
    YouCannotUpdateThisClientAdminWhichHasAlreadyBeenDeleted = -249,// You cannot update this client admin which has already been deleted.
    YouHaveNoPrivilegeToModifyTheRoleOfThisAdmin = -253,// You have no privilege to modify the role of this admin.
    PrivilegeAllowDcvCantBeAddedToNonSslAdmins = -255,// Privilege "Allow DCV" can''t be added to non SSL admins.
    YouHaveNoPrivilegeToAssignDcvPrivileges = -256,// You have no privilege to assign DCV privileges.
    TheRangeIsTooWideMaximumOf0PublicIpportPairsAnd1PrivateIpportPairsPerScanAreAllowed = -303,// The range is too wide. Maximum of {0} public ip-port pairs and {1} private ip-port pairs per scan are allowed.
    IncorrectFormatCidr = -304,// Incorrect format CIDR.
    TheRangeOfIpportPairsIsTooWide = -305,// The range of ip-port pairs is too wide.
    DomainName0Exceeds1CharactersLimit = -306,// Domain name {0} exceeds {1} characters limit.
    Customer0CannotBeFound = -410,// Customer {0} cannot be found.
    Customer0DoesNotHaveALoginNameForCa = -429,// Customer {0} does not have a login name for CA.
    PersonNameCannotBeEmpty = -500,// Person name cannot be empty
    YouCantChangeOrganizationForThisPersonBrKeyEscrowOfItsLevelHasBeenEnabledForEitherCurrentOrganizationdepartmentOrTargetOrganizationdepartment = -507,// You can''t change organization for this person.&lt;br&gt; Key escrow of its level has been enabled for either current organization/department or target organization/department.
    NewPersonPleaseSpecifyName = -508,// New person. Please specify name
    UnknownEmailAddress = -518,// Unknown email address
    YouHaveNoPrivilegeToModifyTheEmailOfThisPerson = -524,// You have no privilege to modify the email of this person.
    AvailableAgentsAreNotConfiguredToScanTheSpecifiedPrivateRanges = -607,// Available Agent(s) are not configured to scan the specified private range(s).
    ToScanYouMustFirstEnterAtLeastOneRangeParameter = -615,// To scan, you must first enter at least one range parameter.
    DiscoveryIsCurrentlyRunningPleaseTryAgainLater = -618,// Discovery is currently running. Please try again later.
    AvailableAgentsAreNotConfiguredToScanTheSpecifiedPublicRanges = -637,// Available Agent(s) are not configured to scan the specified public range(s).
    SuppliedOrgidInvalid = -639,// Supplied orgid invalid..
    SuchDomainAlreadyExists = -700,// Such domain already exists
    ThisOperationCannotBePerformedAsTheDelegationStatusIsOtherThanRequested = -705,// This operation cannot be performed as the delegation status is other than ‘‘Requested’’.
    ThisDomainDelegationRequestHasAlreadyBeenDeleted = -707,// This domain delegation request has already been deleted.
    PleaseDelegateDomainToAtLeastOneOrganizationOrDepartment = -709,// Please delegate domain to at least one organization or department.
    DomainCantBeDelegatedToDeletedOrganization = -711,// Domain can''t be delegated to deleted organization.
    TheDomainNameShouldBeAtLeast0CharactersInLength = -712,// The domain name should be at least {0} characters in length.
    TheDomainNameShouldBeAtMost0CharactersInLength = -713,// The domain name should be at most {0} characters in length.
    TheDomainNameShouldHaveAtLeast0Dots = -714,// The domain name should have at least {0} dots.
    TheDomain0IsInactive = -715,// The domain ''{0}'' is inactive.
    SomethingIsNotAHighlevelDomainOnlyHighlevelDomainsCanBeValidated = -723,// &lt;Something&gt; is not a high-level domain. Only high-level domains can be validated.
    TheRequestFor0CannotBeProcessedSinceItsDomainValidationStatusIs1 = -724,// The request for ''{0}'' cannot be processed since it''s domain validation status is {1}.
    TheDomain0DoesNotExist = -727,// The domain ''{0}'' does not exist.
    OneOrMoreDelegationsHaveBeenChangedByAnotherAdministratorYourChangesWillBeIgnored = -728,// One or more delegations have been changed by another administrator. Your changes will be ignored.
    YouDoNotHaveSufficientPrivilegesToModifyTheNameOfThisDomain = -731,// You do not have sufficient privileges to modify the name of this domain.
    InvalidDomainName = -732,// Invalid domain name.
    TheDomains0AreNotValidatedPleasePerformTheDcvProcessForThemBeforeProceed = -737,// The domain(s): {0} are not validated! Please perform the DCV process for them before proceed.
    AccessDeniedYouAreNotAllowedToPerformThe0OperationOnThisDomain = -738,// Access denied. You are not allowed to perform the {0} operation on this domain.
    ThisOperationCannotBePerformedDueToSslCertificatesEnrolledForThisDomainOrItsSubdomains = -740,// This operation cannot be performed due to SSL certificates enrolled for this domain or its subdomains.
    AccessDeniedDueToDraoRequestThatHasNotBeenApprovedForDomain0ForceDomainCreationIsDisabled = -741,// Access denied due to a DRAOs request that has not been approved for domain {0}. Force domain creation is disabled.
    TheChangesOfClientCertificateProfileSettingsWillCauseTheFollowingDepartmentsHaveBrNoAvailableCustomizedClientCertificateProfileOrCustomizedClientCertificateProfilesHaveNoAvailableTermOrDefaultTerm0 = -834,// The changes of Client Certificate Profile settings will cause the following departments have &lt;br&gt; no available customized Client Certificate Profile, or customized Client Certificate Profiles have no available term or default term: {0}
    TheChangesOfClientCertificateProfileSettingsWillCauseTheUnderLevelsHaveBrNoAvailableCustomizedClientCertificateProfileOrCustomizedClientCertificateProfilesHaveNoAvailableTermOrDefaultTerm = -840,// The changes of Client Certificate Profile settings will cause the under levels have &lt;br&gt; no available customized Client Certificate Profile, or customized Client Certificate Profiles have no available term or default term.
    SslCertificateOfThisTypeCannotBeRequestedDueTo0ValidationStatusOfTheSelectedOrganization = -843,// SSL certificate of this type cannot be requested due to ‘{0}’ validation status of the selected organization.
    AtLeastOneOfTheFollowingFieldsMustBeFilledIn0 = -951,// 'At least one of the following fields must be filled in: {0}.
    IncorrectLoginCredentials = -970,// Incorrect login credentials.
    NewPasswordMustBeBetween0And32Characters = -976,// New password must be between {0} and 32 characters.
    NewPasswordLengthMustBe32Characters = -977,// New password length must be 32 characters.
    NewPasswordMustNotContainLogin = -982,// New password must not contain Login.
    Domain0IsNotAllowed = -1010,// Domain ''{0}'' is not allowed.
    ThisOperationCannotBePerformedForOrganization0 = -1021,// This operation cannot be performed for Organization ''{0}''.
    Organization0NotFound = -1023,// Organization ''{0}'' not found.
    InvalidOrderNumber0 = -1104,// Invalid order number {0}
    NoValidClientCertificatesFoundFor0 = -1108,// No valid client certificates found for {0}.
    CertificateCantBeApprovedCauseItHasState0 = -1112,// Certificate can''t be approved cause it has state = {0}
    CodeNeg1113 = -1113,// {0} certificate is not ready to be applied.
    TheSslIsNull = -1117,// The SSL is null.
    TheDomains0HaveNotBeenValidatedUnderTheDcvProcedure = -1137,// The domain(s) {0} have not been validated under the DCV procedure.
    ErrorWhileCheckingSizeOfPublicKeyInCsr = -1138,// Error while checking size of public key in CSR.
    SinceYouAreARequesterOfThisCertificateYouCantApproveItForEvCertificatesTheRequesterAndTheApproverMustNotBeTheSamePerson = -1140,// Since you are a requester of this certificate you can''t approve it. For EV certificates the requester and the approver must not be the same person.
    SslCertificateId0MustBeRediscoveredDueToMigrationNeedWeAreSorryForInconvenience = -1144,// SSL certificate id: {0} must be re-discovered due to migration need. We are sorry for inconvenience.
    ReplaceIsForbiddenForAutoinstalledCertificates = -1148,// Replace is forbidden for autoinstalled certificates.
    TheRequestIsBeingProcessedBySectigo = -1400,// The request is being processed by Sectigo.
    UnsupportedCertificateFormatSpecified0 = -1450,// Unsupported certificate format specified: {0}
    Field0HasInvalidValue = -1601,// Field ''{0}'' has invalid value.
    ErrorWhileValidatingTheDomain0 = -1603,// Error while validating the domain {0}
    DcvIsNotEnabledForThisCustomer = -1608,// DCV is not enabled for this customer.
    This0WasModifiedOrDeletedByAnotherUser = -3114,// This {0} was modified or deleted by another user.
    This0WasModifiedOrDeletedByAnotherUserPleaseRefreshData = -3115,// This {0} was modified or deleted by another user. Please refresh data.
    InvalidScanRange0 = -3301,// Invalid scan range: {0}
    YouDonTHaveAccessToOrganizationAssignedToTheRule = -5001,// You don' t have access to Organization assigned to the Rule
    AssignmentRulesCannotBeEmpty = -5002,// Assignment rules cannot be empty.
    CannotDeleteAnAssignmentRuleHasBeenAssignedToTheNetDiscoveryTasks0 = -5003,// Cannot delete. An assignment rule has been assigned to the Net Discovery Tasks {0}
    CertificateNotFound0 = -5101,// Certificate not found. {0}
    DeviceCertificateProfileNotFound = -5109,// Device Certificate Profile not found.
    TooManyRequests = 429,// Rate limited
}
