using SectigoCertificateManager.Examples.Examples;

await BasicApiExample.RunAsync();
await SearchCertificatesExample.RunAsync();
await DownloadCertificateExample.RunAsync();
await DownloadCertificateObjectExample.RunAsync();
await DownloadPfxExample.RunAsync();
await DeleteCertificateExample.RunAsync();
await UploadOrdersExample.RunAsync();
await GetCertificateRevocationExample.RunAsync();
await ImportCertificatesExample.RunAsync();
await ListCertificateTypesExample.RunAsync();
await UpsertCertificateTypeExample.RunAsync();
await WatchOrdersExample.RunAsync();
await IncrementalOrderSyncExample.RunAsync();
CsrGeneratorExample.Run();
HttpClientPropertyExample.Run();
GuardExample.Run();
CombineCertKeyToPfxExample.Run();
await StreamCertificatesBytesExample.RunAsync();
await ApiErrorHandlingExample.RunAsync();
